# Generated by Django 5.1.7 on 2025-05-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_pecas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pecas',
        ),
    ]
