# Generated by Django 5.2.1 on 2025-05-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_atividades_usuario_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_verificacao',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
