# Generated by Django 5.2.1 on 2025-05-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do item')),
                ('categoria', models.CharField(choices=[('informatica', 'Informática'), ('eletrodomestico', 'Eletrodoméstico'), ('telefonia', 'Telefonia'), ('audio_video', 'Áudio e Vídeo'), ('outros', 'Outros')], max_length=50, verbose_name='Categoria')),
                ('local', models.CharField(max_length=255, verbose_name='Local de entrega ou coleta')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_coleta/', verbose_name='Foto do item')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
