# Generated by Django 5.1.7 on 2025-05-27 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do item')),
                ('categoria', models.CharField(choices=[('informatica', 'Informática'), ('eletrodomestico', 'Eletrodoméstico'), ('telefonia', 'Telefonia'), ('audio_video', 'Áudio e Vídeo'), ('outros', 'Outros')], default='outros', max_length=50, verbose_name='Categoria')),
                ('local', models.CharField(max_length=255, verbose_name='Local de entrega ou coleta')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_doacao/', verbose_name='Foto do item')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='coleta',
            name='local',
        ),
        migrations.AddField(
            model_name='coleta',
            name='data_preferencial',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data preferencial para coleta'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='endereco',
            field=models.CharField(default='A definir', max_length=255, verbose_name='Endereço para coleta'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Quantidade de itens'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('agendada', 'Agendada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='coleta',
            name='tipo_material',
            field=models.CharField(choices=[('eletronico', 'Eletrônico'), ('metal', 'Metal'), ('plastico', 'Plástico'), ('vidro', 'Vidro'), ('misto', 'Misto')], default='misto', max_length=50, verbose_name='Tipo de Material'),
        ),
    ]
